# Site settings
baseURL = "https://karnapatel.netlify.app/"
languageCode = "en-us"
title = "Portfolio website for Kostis Christodoulou"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Karna Patel"
  description = "Hi, my name is Karna and I am a Canadian currently studying at London Business School!"
  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = ""
    subtitle = "Karna Patel"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Welcome"
      url = "#"

    [[params.navigation.links]]
      name = "Contact"
      url = "blogs"

  #  [[params.navigation.links]]
  #    name = "Generic Blog"
   #   url = "blogs/ipsum"

  #  [[params.navigation.links]]
  #    name = "Elements"
  #    url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
     # name = "Get Started"
      #url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
     # name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Karna Patel"
    subtitle = "Hi, my name is Karna and I am a Canadian currently studying at LBS."
    buttonText = "Learn More"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Work Example"
      subtitle = "Investing Using the CAPE Ratio"
      image = "pic01.jpg"
      url = "projects/project1"

    [[params.tiles.showcase]]
     title = "Karna's Watchlist"
     subtitle = "My Favourite Movies & Tv-Shows"
      image = "pic02.jpg"
      url = "projects/project2"

    [[params.tiles.showcase]]
    title = "Summary of Experience"
    subtitle = "CV"
    image = "pic03.jpg"
     url = "Karna Patel - CV.pdf"

    #[[params.tiles.showcase]]
    #  title = "Ipsum"
    #  subtitle = "Nisl Sed Aliquam"
      #image = "pic04.jpg"
     # url = "blogs/ipsum"

    #[[params.tiles.showcase]]
     # title = "Consequat"
    #  subtitle = "Ipsum Dolor Sit Amet"
      #image = "pic05.jpg"
     # url = "blogs/ipsum"

    #[[params.tiles.showcase]]
    #  title = "Etiam"
      #subtitle = "Feugiat Amet Tempus"
     # image = "pic06.jpg"
    #  url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About Me"
    subtitle = """
    Hello and welcome to my website! I am a Canadian student currently studying finance at London Business School.
    Prior to LBS, I worked in Corporate Development at a cloud accounting software company and also completed multiple internships, 
    including the finance department of one of Canada’s largest charities, the investment research team at a blockchain consulting firm, 
    IBM Canada’s Watson Investment Research Project, and a private equity firm.I completed my undergradute studies from the
    Richard Ivey School of Business in 2019. In my free time, you will probably see my playing basketball and drinking too much coffee."""   
    buttonText = "About Me"
    url = "About"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "karnapatel16@gmail.com"

   # [[params.contact.phone]]
   # title = "Phone"
    #phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
   # title = "Address"
    #street = "Street"
    city = "London | Toronto"
   # country = "Worldwide"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Karna Patel"

    # Uses font awesome icons
   # [[params.footer.social]]
    #  icon = "fa-twitter"
     # url= "https://www.twitter.com"
      #label = "Twitter"

   # [[params.footer.social]]
   #   icon = "fa-facebook"
    #  url= "https://www.facebook.com"
     # label = "Facebook"

    #[[params.footer.social]]
     # icon = "fa-instagram"
      #url= "https://www.instagram.com"
      #label = "Instagram"
    
  #  [[params.footer.social]]
      #icon = "fa-github"
      #url= "https://www.github.com"
    # label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "www.linkedin.com/in/karnap"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
